## Binomial Distributions¶

Use NumPy to create simulations and compute proportions for the following outcomes. The first one is done for you

In [1]:
import numpy as np

###  A fair coin flip produces heads

In [15]:
# simulate 1 million tests of one fair coin flip
# remember, the output of these tests are the # successes, or # heads
tests=np.random.binomial(1,0.5, int(1e6))
tests.shape

(1000000,)

In [19]:
tests

array([0, 0, 0, ..., 0, 1, 1])

In [16]:
(tests==1).mean()

0.499945

###  Five fair coin flips produce exactly one head

In [17]:
# simulate 1 million tests of five fair coin flips
test2=np.random.binomial(5,0.5, int(1e6))
test2.shape

(1000000,)

In [18]:
test2

array([3, 2, 3, ..., 2, 3, 0])

In [21]:
# proportion of tests that produced 1 head
(test2==1).mean()

0.155944

### Ten fair coin flips produce exactly four heads

In [23]:
# simulate 1 million tests of ten fair coin flips
test3=np.random.binomial(10,0.5, int(1e6))
test3

array([2, 5, 3, ..., 4, 3, 3])

In [25]:
# proportion of tests that produced 4 heads
(test3==4).mean()

0.205734

### Five bias coin flips with P(H) = 0.8 produce exactly five heads

In [26]:
# simulate 1 million tests of five bias coin flips
test4 = np.random.binomial(5, 0.8, int(1e6))

# proportion of tests that produced 5 heads
(test4 == 5).mean()

0.327445

In [27]:
test4

array([2, 3, 5, ..., 4, 5, 3])

### Ten bias coin flips with P(H) = 0.15 produce at least 3 heads

In [31]:

# simulate 1 million tests of ten bias coin flips
test5=np.random.binomial(10,0.15, int(1e6))

In [32]:
test5

array([1, 3, 3, ..., 1, 2, 0])

In [34]:
(test5 >= 3).mean()

0.18028