# Probability / Coin Flips and Die Rolls

In [1]:
# import numpy
import numpy as np

### 1. Two fair coin flips produce exactly two heads

In [14]:
# simulate 1 million tests of two fair coin flips
tests = np.random.randint(2, size=(int(1e6), 2))

# sums of all tests
test_sums = tests.sum(axis=1)

# proportion of tests that produced exactly two heads
(test_sums == 0).mean()

0.250196

In [8]:
tests.shape

(1000000, 2)

In [10]:
test_sums.shape

(1000000,)

In [11]:
test_sums

array([1, 1, 1, ..., 1, 1, 1])

In [12]:
tests

array([[0, 1],
       [1, 0],
       [0, 1],
       ...,
       [1, 0],
       [1, 0],
       [0, 1]])

### 2. Three fair coin flips produce exactly one head

In [22]:
# simulate 1 million tests of three fair coin flips
tests2 = np.random.randint(2, size=(int(1e6), 3))

# sums of all tests
test2_sums = tests2.sum(axis=1)

# proportion of tests that produced exactly one head
(test2_sums == 2).mean()

0.374028

In [18]:
tests2

array([[1, 0, 1],
       [1, 1, 0],
       [0, 1, 0],
       ...,
       [1, 1, 0],
       [1, 0, 0],
       [1, 1, 1]])

In [19]:
test2_sums

array([1, 1, 2, ..., 0, 1, 1])

### 3. Three bias coin flips with P(H) = 0.6 produce exactly one head

In [21]:
# simulate 1 million tests of three bias coin flips
# hint: use np.random.choice()
tests3 = np.random.choice([0, 1], size=(int(1e6), 3), p=[0.6, 0.4])

# sums of all tests
test3_sums = tests3.sum(axis=1)

# proportion of tests that produced exactly one head
(test3_sums == 2).mean()

0.287785

### 4. A die rolls an even number

In [23]:
# simulate 1 million tests of one die roll
tests4 = np.random.choice(np.arange(1, 7), size=int(1e6))

# proportion of tests that produced an even number
(tests4 % 2 == 0).mean()

0.499788

### 5. Two dice roll a double

In [25]:
# simulate the first million die rolls
first = np.random.choice(np.arange(6), size=int(1e6))

# simulate the second million die rolls
second = np.random.choice(np.arange(6), size=int(1e6))

# proportion of tests where the 1st and 2nd die rolled the same number
(first == second).mean()

0.166443

In [27]:
first.shape

(1000000,)

In [29]:
second

array([3, 3, 1, ..., 1, 1, 3])